### ISSUE TITLE
Code Bug in LSTM & GRU layers

### ISSUE THREAD

**Issue by zhuohan123** [fyabc/DL4NMT_Theano#3]
In `libs/layers/lstm.py`, line 158

~~~python
    n_steps = state_below.shape[0]
    n_samples = state_below.shape[1] if state_below.ndim == 3 else 1
~~~

If `state_below.ndim == 3`, the code is correct. But when `state_below.ndeim == 2` (in one_step mode), `n_steps` should be 2, and `n_samples` should be `state_below.shape[0]`. In a word, the correct code should be

~~~python
    n_steps = state_below.shape[0] if state_below.ndim == 3 else 1
    n_samples = state_below.shape[1] if state_below.ndim == 3 else state_below.shape[0]
~~~

The Same bug occurs at line 358, and also in `libs/layers/gru.py`.

This bug will not affect the execution of the code, but I think it's better to fix it for clarity. Thanks.

**Comment by ustctf-zz** [comment]
Thank zhuohan very much!

@fyabc Would you please check this issue?

**Comment by fyabc** [comment]
Bug fixed. Thanks!
